create bot and db
RomanOdobesku/fintech-hub-chatbot pull request #1
Opened 2024-03-23 11:26 UTC by olya-antre

Основа для бота (пока поднимается только локально) и черновик для создания базы данных с залитым в нее самым первым датасетом (без текста новостей и его саммари).

2024-03-24 10:56 UTC, RomanOdobesku requested changes

2024-03-24 10:56 UTC, RomanOdobesku commented on src/backend/fill_database_from_dataset.py
> +engine = create_engine("sqlite:///my_base.db", echo=True)
Я так понял, у нас пока in-memory база, ты отдельно её в докере не поднимаешь?

2024-03-24 10:56 UTC, RomanOdobesku commented on src/backend/fill_database_from_dataset.py
> +category_list = ["cr",
Возможно, стоит сделать конфиг и перенести это в него

2024-03-24 10:56 UTC, RomanOdobesku commented on src/backend/fill_database_from_dataset.py
> +    cat1 = select(Categories.id).where(Categories.name == cat)
Переименуй cat1 плиз

2024-03-24 10:56 UTC, RomanOdobesku commented on src/backend/fill_database_from_dataset.py
> +    cat = session.execute(cat1).first()
Тут, кажется, идёт перезапись переменной cat. Если так должно быть, добавь коммент почему, если нет - переименуй плиз.

2024-03-24 10:56 UTC, RomanOdobesku commented on src/backend/models.py
> +    URL = Column(String(200), nullable=False)
Давай мб для единообразия URL в нижнем регистре сделаем?

2024-03-24 10:56 UTC, RomanOdobesku commented on src/backend/models.py
> +    nick_name = Column(String(100))
Мб username?

2024-03-24 10:56 UTC, RomanOdobesku commented on src/backend/models.py
> +class User_categories(Base):
Мб UserCategories? Так будет чуть более по-питоновски. Если это имя в БД и будут проблемы, то можно оставить.

2024-03-24 10:56 UTC, RomanOdobesku commented on src/tg_bot/bot_database/db_query.py
> +async def orm_get_categories_from_name(session: AsyncSession,
Проставь плиз в функциях тип возвращаемых значений и docstring. За типизацию параметров лайк)

2024-03-24 10:56 UTC, RomanOdobesku commented on src/tg_bot/bot_database/models.py
> +
Не очень понял, а зачем нам ещё одна табличка? В backend вроде всё то же самое

2024-03-24 10:56 UTC, RomanOdobesku commented on src/tg_bot/common/bot_cmds_list.py
> +private = [
Это должно называться private?

2024-03-24 11:03 UTC, olya-antre commented on src/backend/fill_database_from_dataset.py
> +engine = create_engine("sqlite:///my_base.db", echo=True)
Да, пока in-memory, на данном этапе не вижу необходимости отдельно поднимать субд

2024-03-24 11:05 UTC, RomanOdobesku commented on src/backend/fill_database_from_dataset.py
> +category_list = ["cr",
Конфиг только ради этого не нужен, если есть что ещё туда перенести - тогда надо

2024-03-24 11:06 UTC, RomanOdobesku commented on src/backend/fill_database_from_dataset.py
> +engine = create_engine("sqlite:///my_base.db", echo=True)
Хорошо, принято

2024-03-24 11:15 UTC, olya-antre commented on src/backend/fill_database_from_dataset.py
> +category_list = ["cr",
Конфиг как бы есть, просто я не закинула файлик .env. Там пока только токен для нашего бота, можно добавить и список категорий. Просто закидывать в публичный репозиторий токен бота наверное не стоит...

2024-03-24 11:17 UTC, olya-antre commented on src/tg_bot/bot_database/db_query.py
> +async def orm_get_categories_from_name(session: AsyncSession,
Все напишу, не сразу сделала, так как много раз переписываю одни и те же функции

2024-03-24 11:37 UTC, RomanOdobesku commented on src/backend/fill_database_from_dataset.py
> +category_list = ["cr",
Не, dotenv это именно секреты, не конфиг. Конфиг - это просто параметры для запуска, которые могут поменяться. Ну т.е. там можно всякие гиперпараметры указывать или вот набор категроий, с которыми мы работаем. Можно конфиг реализовать просто как питоновский класс Config, а объект создавать в точке входа в программу. Суть в том, что ты все кофигурирумеые парметры собираешь в одном месте, чтобы не искать и не менять (при необходимости) по всему проекту

2024-03-24 11:38 UTC, olya-antre commented on src/tg_bot/bot_database/models.py
> +
Были некоторые траблы с импортированием нужных модулей из backend, вроде уже решила эту проблему

2024-03-24 11:41 UTC, RomanOdobesku commented on src/tg_bot/bot_database/models.py
> +
Хорошо, тогда сделай следующий коммит в эту же ветку, он должен сразу в этот пул реквест попасть

2024-03-24 11:41 UTC, olya-antre commented on src/tg_bot/common/bot_cmds_list.py
> +private = [
Это набор команд у приватных чатов с ботом (он же может еще использовать в беседах на нескольких человек), но если название не нравится, то я переименовала)

2024-03-24 11:58 UTC, olya-antre commented on src/backend/fill_database_from_dataset.py
> +category_list = ["cr",
Окей, тогда нет смысла создавать пока config только для такого списка. Если потом что-то нужно будет добавить, создадим.

2024-03-24 16:39 UTC, RomanOdobesku requested changes

2024-03-24 16:39 UTC, RomanOdobesku commented on draft.txt
> +import asyncio
draft.txt можно убрать думаю)

2024-03-24 16:39 UTC, RomanOdobesku commented on draft.txt
> +```
:)

2024-03-24 16:39 UTC, RomanOdobesku commented on src/tg_bot/bot_database/db_query.py
> +from backend.models import Users, Categories, UserCategories, News
обычно импорты делают через полный путь до пакета, т.к. запускают из расчёта что мы находимся в корне проекта
т.е. from src.backend.models
Где точка входа в программу и как ты её запускаешь?

2024-03-24 16:39 UTC, RomanOdobesku commented on src/tg_bot/common/bot_cmds_list.py
> +command_for_private_channels = [
commands_for_private_channels

2024-03-24 17:22 UTC, olya-antre commented on src/tg_bot/bot_database/db_query.py
> +from backend.models import Users, Categories, UserCategories, News
Да, был момент, сделала main.py, пока будем через него запускать.

2024-03-24 17:22 UTC, olya-antre commented on draft.txt
> +```
Какой внимательный!

2024-03-24 17:22 UTC, olya-antre commented on draft.txt
> +import asyncio
Тут ничего не было =)

2024-03-24 17:29 UTC, RomanOdobesku requested changes

2024-03-24 17:29 UTC, RomanOdobesku commented on main.py
> +asyncio.run(bot.main())
Огонь, всё хорошо. Единственное - перемести всё-таки main.py в src/tg_bot, тк это его мейн
Если не будет работать запуск, попробуй python -m src.tg_bot.main

2024-03-24 17:32 UTC, RomanOdobesku commented on main.py
> +asyncio.run(bot.main())
Кстати, резолв по-хорошему должен нажимать тот же, кто создал тред. Это так, на будущее)

2024-03-24 20:19 UTC, olya-antre commented on main.py
> +asyncio.run(bot.main())
По резолвам - окей), по поводу переноса: я думаю туда добавить и код по поднятию бд (сейчас создание / подключение / заполнение происходит при отдельном запуске fill_database, т.к. пока копаюсь в боте, удобно не трогать бд), потому и закинула отдельно. Или мы хотим в разные моменты запускать бота и поднимать бд?

2024-03-24 20:23 UTC, RomanOdobesku commented on main.py
> +asyncio.run(bot.main())
вообще бд должна жить отдельной жизнью в отдельном докер контейнере, так что они явно запускаются в разное время

2024-03-26 17:33 UTC, RomanOdobesku approved these changes

2024-03-26 17:49 UTC, RomanOdobesku approved these changes

2024-03-26 17:50 UTC, merged