Parser
RomanOdobesku/fintech-hub-chatbot pull request #2
Opened 2024-03-24 22:16 UTC by ALeksandr13254

2024-03-25 15:44 UTC, RomanOdobesku requested changes
Привет! Спасибо за пул реквест, у меня будет несколько правок

2024-03-25 15:44 UTC, RomanOdobesku commented on src/parser/news aggreagtor parser.py
> +# !pip -qq install selenium_driverless
1. Плиз добавь описание к пул реквесту с подробным описанием
2. Давай зафиксируем зависимости в requirements.txt

2024-03-25 15:44 UTC, RomanOdobesku commented on src/parser/news aggreagtor parser.py
> +content_publisher = driver.find_elements(By.CLASS_NAME, "article-publisher__name u-right-spacer-xs")
Добавь плиз комментов здесь и в других неочевидных местах. Сложно понять что происходит, когда первый раз это видишь

2024-03-25 15:44 UTC, RomanOdobesku commented on src/parser/news aggreagtor parser.py
> +for i in range(min([len(content_news), len(content_title), len(content_time), len(content_publisher)])):
Я так понял, что у тебя есть списки с разным контентом, но при этом у них мб разная длина, и здесь в форике ты идёшь до минимальной длины этих списков. Вопрос: а точно ли у тебя тогда весь контент согласуется между собой, не может быть такого что content_news[i] относится не к той же новости, что, например, content_title[i]? Почему какой-то из списков может вдруг быть меньше?

2024-03-25 15:44 UTC, RomanOdobesku commented on src/parser/news aggreagtor parser.py
> +    article_keywords = article.keywords
тоже комменты где используешь стороннюю библиотеку

2024-03-27 14:57 UTC, ALeksandr13254 commented on src/parser/news aggreagtor parser.py
> +# !pip -qq install selenium_driverless
Зафиксировал зависимости в requirements.txt

2024-03-27 14:57 UTC, ALeksandr13254 commented on src/parser/news aggreagtor parser.py
> +content_publisher = driver.find_elements(By.CLASS_NAME, "article-publisher__name u-right-spacer-xs")
Добавил комментарии к каждой строчке

2024-03-27 14:58 UTC, ALeksandr13254 commented on src/parser/news aggreagtor parser.py
> +for i in range(min([len(content_news), len(content_title), len(content_time), len(content_publisher)])):
Исправил, теперь всё должно согласовываться

2024-03-27 14:58 UTC, ALeksandr13254 commented on src/parser/news aggreagtor parser.py
> +    article_keywords = article.keywords
Добавил комментарии к каждой строчке

2024-03-27 16:34 UTC, RomanOdobesku requested changes

2024-03-27 16:34 UTC, RomanOdobesku commented on src/parser/manual parser.py
>  def parsing_www_rba_gov_au(check_years: int, date_news: datetime = datetime.now()) -> list:
Добавь плиз docstring (в т.ч. с описанием аргументов - их смысла, что они делают) и комменты в этой и других функциях.

2024-03-27 16:34 UTC, RomanOdobesku commented on src/parser/manual parser.py
>  def parsing_www_rba_gov_au(check_years: int, date_news: datetime = datetime.now()) -> list:
Не могу почему-то писать комменты в большей части кода ниже, напишу здесь. Вопрос к захардкоженным числам в коде. 
Например:
for num_news in range(1, 51):
            if num_news < 10:
Либо комменты почему это так, либо превратить их в аргументы функции и описать их в docstring

2024-03-27 16:34 UTC, RomanOdobesku commented on src/parser/manual parser.py
>  def parsing_www_rba_gov_au(check_years: int, date_news: datetime = datetime.now()) -> list:
article.nlp() - что оно делает, как долго, и нужно ли оно нам

2024-03-27 16:34 UTC, RomanOdobesku commented on src/parser/news aggregator parser.py
> +def news_aggregator_parser():
Спасибо, здесь всё хорошо)

2024-03-27 16:34 UTC, RomanOdobesku commented on src/parser/news aggregator parser.py
> +        article.nlp()
article.nlp() делает нам summary и keywords? Что конкретно делает строчка? Сколько она занимает времени и нужно ли это нам?

2024-03-27 16:34 UTC, RomanOdobesku commented on src/parser/news aggregator parser.py
> +print(news_aggregator_parser())
```python
if __name__ == '__main__':
```

2024-03-27 16:34 UTC, RomanOdobesku commented on src/parser/manual parser.py
> +    json.dump(list_json, file, indent=3)
Добавь сюда 
```python
if __name__ == '__main__':
```
Иначе при импорте функций из файла у тебя это тоже будет вызываться

2024-03-27 16:34 UTC, RomanOdobesku commented on src/parser/manual parser.py
> +    list_news.extend(parsing_www_hkma_gov_hk(check_days=7))
Тут захардкожены значения, их можно вынести в аргументы функции manual_parsing. Саму функцию (вместе с файлом) предлагаю переименовать. Назвать это various_sources_parsing например. Из ручного тут только прописывание логики работы парсера, с точки зрения использования функций мы ничего ручного не делаем, название не информативное получается

2024-03-27 16:34 UTC, RomanOdobesku commented on src/parser/manual parser.py
>  def manual_parsing() -> list:
в формате возвращаемых значений список по-другому пишется (и указывается тип значений списка):
from typing import List
def generate_list(...) -> List[int]:

2024-03-27 16:34 UTC, RomanOdobesku commented on src/parser/requirements.txt
> +newspaper3k
Зафиксируй версии плиз

2024-03-29 13:41 UTC, ALeksandr13254 commented on src/parser/manual parser.py
>  def parsing_www_rba_gov_au(check_years: int, date_news: datetime = datetime.now()) -> list:
> Не могу почему-то писать комменты в большей части кода ниже, напишу здесь. Вопрос к захардкоженным числам в коде. Например: for num_news in range(1, 51): if num_news < 10: Либо комменты почему это так, либо превратить их в аргументы функции и описать их в docstring

Для парсинга этих 4-х сайтов использовался перебор ссылок. В самих ссылках даты нет, есть только номера их выхода. Обычно за год на этом сайте не бывает больше 50 публикаций...

2024-03-29 13:44 UTC, ALeksandr13254 commented on src/parser/manual parser.py
>  def parsing_www_rba_gov_au(check_years: int, date_news: datetime = datetime.now()) -> list:
> article.nlp() - что оно делает, как долго, и нужно ли оно нам

Выполняется меньше секунды на новость. Думал вдруг будет полезна, если нет, то я уберу.

2024-03-29 13:53 UTC, ALeksandr13254 commented on src/parser/manual parser.py
>  def parsing_www_rba_gov_au(check_years: int, date_news: datetime = datetime.now()) -> list:
> Добавь плиз docstring (в т.ч. с описанием аргументов - их смысла, что они делают) и комменты в этой и других функциях.

Я уже не вижу особого смысла на парсинге этих 4 сайтов останавливаться, так как вряд-ли мы вообще эти парсеры будем использовать. После них я сделал парсер агрегатора новостей, поэтому необходимость в этом коде наверное отпала, так как я просто проверял саму возможность такого парсинга. Я его наверное просто напрямую закину, чтобы он глаза не мозолил в пулл реквесте.

2024-03-29 13:53 UTC, ALeksandr13254 commented on src/parser/requirements.txt
> +newspaper3k
+

2024-03-29 13:56 UTC, ALeksandr13254 commented on src/parser/manual parser.py
> +    list_news.extend(parsing_www_hkma_gov_hk(check_days=7))
Переименовал. Тут есть проблема с логикой работы этой функции, которая объединяет 4 парсера. Сами парсеры в силу их специфики работы (через умный перебор url) и специфики сайтов (на каких-то выходят новости каждый день, на каких-то публикации рах в квартал), с которых они парсят, получились ну очень разными... Поэтому наверное их вообще не стоило в одну функцию определять...

2024-03-29 13:57 UTC, ALeksandr13254 commented on src/parser/manual parser.py
> +    json.dump(list_json, file, indent=3)
Понял, поправил, спасибо.

2024-03-29 13:57 UTC, ALeksandr13254 commented on src/parser/news aggregator parser.py
> +print(news_aggregator_parser())
И тут тоже поправил)

2024-03-29 14:26 UTC, RomanOdobesku requested changes

2024-03-29 14:26 UTC, RomanOdobesku commented on src/parser/various sources parsing.py
> +def parsing_www_rba_gov_au(check_years: int, date_news: datetime = datetime.now()) -> List[Dict[str, str]]:
Всё-таки сделай плиз докстринги, это 10 минут времени (3 с современными технологиями). Иногда хорошо написанный docstring позволяет почти избавиться от дополнительных комментариев в коде

2024-03-29 14:26 UTC, RomanOdobesku commented on src/parser/various sources parsing.py
> +            if num_news < 10:
Константы тогда вынеси как параметры функции с дефолтными значениями

2024-03-29 14:26 UTC, RomanOdobesku commented on src/parser/various sources parsing.py
> +                break
тут именно break или continue или мы не должны вообще ничего возвращать? (здесь и в других местах)

2024-03-29 14:26 UTC, RomanOdobesku commented on src/parser/various sources parsing.py
> +                print(f"status_code 404: {article_url}")
Для таких целей используется logger. Там есть разные уровни: info, warning, error, можно время выводить, да и логирование в файлик / stdout можно настраивать.

Обычно делается так: заводится в src отдельный файлик logger.py, в котором примерно такое содержание:
import logging
import sys

LOGGER = logging.getLogger('logger')
LOGGER.setLevel(logging.INFO)
handler = logging.StreamHandler(stream=sys.stdout)
handler.setFormatter(logging.Formatter(fmt='[%(asctime)s: %(levelname)s] %(message)s'))
LOGGER.addHandler(handler)

Потом просто импортируешь этот объект логгера в других файликах и его используешь, например:
except Exception as e:
            LOGGER.error(str(e))

2024-03-29 14:26 UTC, RomanOdobesku commented on src/parser/various sources parsing.py
> +                print(f"status_code 404: {article_url}")
замени плиз здесь и в других местах

2024-03-29 14:26 UTC, RomanOdobesku commented on src/parser/various sources parsing.py
> +def manual_parsing() -> list:
List здесь и в других местах

2024-03-29 14:26 UTC, RomanOdobesku commented on src/parser/various sources parsing.py
> +def manual_parsing() -> list:
переименовать manual parsing, добавить параметры, которые используются внутри

2024-03-29 14:26 UTC, RomanOdobesku commented on src/parser/manual parser.py
>  def manual_parsing() -> list:
не исправлено

2024-03-29 14:27 UTC, RomanOdobesku commented on src/parser/manual parser.py
> +    list_news.extend(parsing_www_hkma_gov_hk(check_days=7))
не исправлено

2024-03-29 14:27 UTC, RomanOdobesku commented on src/parser/manual parser.py
>  def parsing_www_rba_gov_au(check_years: int, date_news: datetime = datetime.now()) -> list:
исправь плиз, чистота кода важна

2024-03-29 14:47 UTC, ALeksandr13254 commented on src/parser/various sources parsing.py
> +                break
На этом сайте url адреса идут по порядку и есть такого url нет, то дальше перебирать нечего и поэтому там именно break.

2024-03-29 16:00 UTC, ALeksandr13254 commented on src/parser/various sources parsing.py
> +                print(f"status_code 404: {article_url}")
Заменил все print на logger. Спасибо за развёрнутое объяснение с кодом!

2024-03-29 16:21 UTC, RomanOdobesku approved these changes
Огонь, спасибо)

2024-03-29 16:21 UTC, merged